force-app/main/default/objects/TwilioMessagesSObjectConfig__mdt/TwilioMessagesSObjectConfig__mdt.object-meta.xml
<CustomObject>
    <description>Configuration object for setting the field that contains the phone number to use towards the Twilio messages service.</description>
    <label>TwilioMessagesSObjectConfig</label>
    <pluralLabel>TwilioMessagesSObjectConfig</pluralLabel>
</CustomObject>

force-app/main/default/objects/TwilioMessagesSObjectConfig__mdt/fields/SObjectName__c.field-meta.xml
<CustomField>
    <fullName>SObjectName__c</fullName>
    <description>The API name of the SObject</description>
    <label>SObjectName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TwilioMessagesSObjectConfig__mdt/fields/TwilioPhoneNoField__c.field-meta.xml
<CustomField>
    <fullName>TwilioPhoneNoField__c</fullName>
    <description>Field that should be fetched from the sobject to be used towards the twilio message service</description>
    <label>TwilioPhoneNoField</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TwilioMessageListController.cls
public class TwilioMessageListController {

    @AuraEnabled
    public static String getPhoneNo(String sObjectName, String recordId){
        String phoneNoField = getPhoneNoFieldBasedOnSObject(sObjectName);

        String query = 'SELECT ' + phoneNoField + ' FROM ' + sObjectName + ' WHERE Id =' + '\'' + recordId + '\'';
        SObject sobj = (SObject) Database.query(query)[0];
        return String.valueOf(sobj.get(phoneNoField));
    }

    private static String getPhoneNoFieldBasedOnSObject(String sObjectName) {
        Map<String, TwilioMessagesSObjectConfig__mdt> twilioMessagesSobjectConfig = new Map<String, TwilioMessagesSObjectConfig__mdt>([
            SELECT 
            SObjectName__c, TwilioPhoneNoField__c  
            FROM TwilioMessagesSObjectConfig__mdt
        ]);

        Map<String, String> phoneFieldBySObjectName = new Map<String, String>();

        for (TwilioMessagesSObjectConfig__mdt tmsc : twilioMessagesSobjectConfig.values()) {
            phoneFieldBySObjectName.put(tmsc.SObjectName__c, tmsc.TwilioPhoneNoField__c);
        }

        System.debug('twilioMessagesSobjectConfig = ' + twilioMessagesSobjectConfig);

        return phoneFieldBySObjectName.get(sObjectName);
    }

    @AuraEnabled
    public static String getTwilioMessages (Map<String, String> filters){
        return TwilioService.getMessages(filters);
    }


}